import Layout from "@/components/layout"
import { getSortedPostData, getActiveCategories, getActiveCategoryIds } from "@/utils/posts"
import Head from "next/head"
import PostList from "@/components/post-list"
import { useState } from "react"

export default function CategoryPage({ activeCategories, postsFilteredByCategory }) {
  const [searchString, setSearchString] = useState('')

  return (
    <Layout 
      activeCategories={activeCategories}
      searchString={searchString}
      setSearchString={setSearchString}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostList 
        posts={postsFilteredByCategory} 
        searchString={searchString} 
      />
    </Layout>
  )
}

export function getStaticPaths() {
  const paths = getActiveCategoryIds()

  return {
    paths,
    fallback: false
  }
}

export function getStaticProps({ params }) {
  const allPostsData = getSortedPostData()
  const activeCategories = getActiveCategories()

  const postsFilteredByCategory = allPostsData.filter(post => post.category == params.id)

  return {
    props: {
      postsFilteredByCategory,
      activeCategories
    }
  }
}