import { getActiveCategoryIds } from "@/utils/posts"
import Layout from "@/components/layout"
import { getSortedPostData, getActiveCategories } from "@/utils/posts"
import Head from "next/head"
import Post from "@/components/post"

export default function CategoryPage({ activeCategories, postsFilteredByCategory }) {
  return (
    <Layout activeCategories={activeCategories}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {postsFilteredByCategory.map((postData) => (
        <Post key={postData.id} postData={postData} />
      ))}
    </Layout>
  )
}

export function getStaticPaths() {
  const paths = getActiveCategoryIds()

  return {
    paths,
    fallback: false
  }
}

export function getStaticProps({ params }) {
  const allPostsData = getSortedPostData()
  const activeCategories = getActiveCategories()

  const postsFilteredByCategory = allPostsData.filter(post => post.category == params.id)

  return {
    props: {
      postsFilteredByCategory,
      activeCategories
    }
  }
}