import Head from 'next/head'
import Layout from '@/components/layout'
import { getSortedPostData, getActiveCategories } from '@/utils/posts'
import { useState } from 'react'
import PostList from '@/components/post-list'

export default function Home({ allPostsData, activeCategories }) {
  const [searchString, setSearchString] = useState('')

  return (
    <Layout 
      activeCategories={activeCategories}
      searchString={searchString}
      setSearchString={setSearchString}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostList 
        posts={allPostsData} 
        searchString={searchString} 
      />
    </Layout>
  )
}

export function getStaticProps() {
  const allPostsData = getSortedPostData()
  const activeCategories = getActiveCategories()
  
  return {
    props: {
      allPostsData,
      activeCategories
    }
  }
}