import Head from 'next/head'
import Link from 'next/link'
import Layout from '@/components/layout'
import { Inter } from '@next/font/google'
import { getSortedPostData } from '@/utils/posts'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ allPostsData }) {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {allPostsData.map(({ id, title, date }) => (
          <li key={id}>
            <Link href={`/${id}`}>{title}</Link>
            <h2>{date}</h2>
          </li>
        ))}
      </ul>
    </Layout>
  )
}

export function getStaticProps() {
  const allPostsData = getSortedPostData()


  console.log(allPostsData)
  return {
    props: {
      allPostsData
    }
  }
}